server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka    
spring:
  application:
    name: api-gateway
  #cloud:
   # gateway:
    #  discovery:
     #   locator:
      #    enabled: true #Ativando gateway para chamar os microsserviços pelo nome
       #   lower-case-service-id: true #Vai aceitar o nome do microsserviço minúsculo