server:
  port : 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/juannobert/config-server
          default-label: main #nome da branch
          search-paths:
          - 'greeting-service*' #caminho utilizado